name: 'Execução Manual'
# regra de disparo( gatilhos/triggers) para execução manual
# gatinho de execução manual = workflow_dispatch
on:
  workflow_dispatch:


jobs:
  e2e-tests:
    name: 'Executar Testes E2E'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalar yarn
        run: npm install -g yarn

      - name: Instalar dependências
        run: yarn

      - name: Instalar Playwright
        run: yarn playwright install

      - name: Executando Testes E2E
        run: yarn run e2e